global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:8001"]
    metrics_path: /metrics

  - job_name: "inventory-service"
    static_configs:
      - targets: ["inventory-service:8002"]
    metrics_path: /metrics

  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-service:8003"]
    metrics_path: /metrics

  - job_name: "fulfillment-worker"
    static_configs:
      - targets: ["fulfillment-worker:8004"]
    metrics_path: /metrics
