server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/orders/ {
        proxy_pass http://order-service:8001/;
    }

    location /api/inventory/ {
        proxy_pass http://inventory-service:8002/;
    }

    location /api/payments/ {
        proxy_pass http://payment-service:8003/;
    }
}
